### PR TITLE
Implement multiplication by scalar and negation on waveforms

### LINKED ISSUE #98: Special operators for waveforms
I think it would be a nice improvement to have some special operators for waveforms. I came up with these ones:
 - Negation: Doing `-wf` would return a Waveform with all it's samples' sign flipped
 - Multiplication: Doing `wf * 2` would multiply all it's values by 2. It doesn't make sense to multiply two waveforms.
 
 Not so sure these make sense:
 - Addition: Doing `wf + 2` would add 2 to all values. `wf1 + wf2` would concatenate two waveforms.
 - Absolute value
 - Power
 - Modulo

Feel free to discuss the pertinence of each or add more suggestions.

### PR DESCRIPTION
**Pull request by HGSilveri**
Implements negation, scalar multiplication and scalar division of waveforms. 

All operations change the waveform's samples, not the duration.

Closes #98 .

### CODE REVIEW

**Comment by HGSilveri** [comment]
@Louis-PaulHenry , are you up for another review?

**Comment by Louis-PaulHenry** [comment]
Sure, I'll have a look

**Review by Louis-PaulHenry — APPROVED** [review]
Seems to be doing what we discussed (simple enough I guess!). Now that it's easy to rescale waveforms, would there be a use for a `renormalize`method that sets the total area to `area=1` (or a user defined value?

**Comment by HGSilveri** [comment]
> Seems to be doing what we discussed (simple enough I guess!). Now that it's easy to rescale waveforms, would there be a use for a `renormalize`method that sets the total area to `area=1` (or a user defined value?

Thanks for the review! I think that could be useful, but it might not make sense for every waveform (i.e. a `RampWaveform` going from negative to positive can have an area of 0). Do you want to open an issue laying out what you had in mind?

**Pull request merged**
