### PR TITLE
Change EmuTN default sampling rate

### PR DESCRIPTION
**Pull request by lvignoli**
The default sampling rate, inherited from `EmulatorConfig`  defaults, is 1.

If I am not mistaken, this translates to `dt=1` for the EmuTN job runned by cloud services, which is not a viable value.

I open this MR not for a blind merge, but rather to make sure the above interpretation of `sampling_rate` for EmuTnBackend is right, and reflect on a good default value.

### CODE REVIEW

**Comment by awennersteen** [comment]
Actually this might not be sufficient, EmuTN does not use a sampling rate but rather dt, so I think maybe this interface isn't correct. I've not really reviewed or used it so not sure. 

EmuTN uses a `dt` value which is the time in nanoseconds of the timestep used during integration. the default value is `10`, and indeed `1` is very low for most purposes. a value < 1 is also not permitted (it must be a a positive integer)

**Comment by HGSilveri** [comment]
There is an internal conversion from `sampling_rate` to `dt`: `dt = 1/ sampling_rate`. So, `dt` is never < 1. If having `dt=10` is a better default than `dt=1`, then I'm okay with changing the default sampling rate to `0.1`, as this PR suggests.

**Comment by HGSilveri** [comment]
@awennersteen Can `dt` assume a non-integer value?

**Comment by lvignoli** [comment]
The docstring should be updated to reflect the fact that sampling_rate must be quite small for EmuTNBackend (≥ 1e-1) to use the backend properly.

**Comment by HGSilveri** [comment]
> The default value for for dt in EmuTN (the `-t` flag) is 10.0, so I would say `sampling_rate=0.1` is a saner default.

My original intention with `EmulatorConfig` was to uniformize all the emulator configs as much as possible (with the rationale that switching the EmulatorBackend while keeping the default config should introduce as few changes as possible). 

That being said, I'm not opposed to this change, I'll defer to your judgement on it.

**Comment by HGSilveri** [comment]
> The docstring should be updated to reflect the fact that sampling_rate must be quite small for EmuTNBackend (≥ 1e-1) to use the backend properly.

Do you mean <= 1e-1? And what do you mean by "properly"?

**Comment by lvignoli** [comment]
Yes, smaller than, I edited the comment.

Properly here meaning with acceptable default runtime.

**Comment by HGSilveri** [comment]
> Yes, smaller than, I edited the comment.
> 
> Properly here meaning with acceptable default runtime.

Ok, gotcha, feel free to add this info to the docstring.

**Comment by awennersteen** [comment]
> @awennersteen Can dt assume a non-integer value?
apparently yes. I was speaking out of habit way in the past when it was an integer. I just checked and we expect a float.

as Louis says setting sampling_rate so that `dt=10` is much better, and most uses cases will want such a timestep. `dt=1` would be quite exceptional

**Comment by lvignoli** [comment]
@HGSilveri some test are failing about "good arguments", I am not sure how to fix them.

**Review by HGSilveri — APPROVED** [review]
LGTM, thanks!

**Comment by HGSilveri** [comment]
Oh damn, the new matplotlib release has type hints 😨

**Pull request merged**
