### PR TITLE
Change instances of `.format` to f-strings [unitaryHACK]

### PR DESCRIPTION
**Pull request by Yash-10**
Hello,

This PR tries to make a small change by making strings consistent by replacing the `.format` syntax with f-strings.

Thanks!

### CODE REVIEW

**Comment by HGSilveri** [comment]
Hi @Yash-10 ! Thanks for the contribution! Are you coming from UnitaryHack?

**Comment by Yash-10** [comment]
Thanks for the opportunity! Yes, I am coming from UnitaryHack. I am hoping to solve issue(s) labelled for UnitaryHack too! I thought of this small change while I was going through the source code.

Could you let me know your thoughts? :)

**Comment by HGSilveri** [comment]
> Thanks for the opportunity! Yes, I am coming from UnitaryHack.

Then don't forget to write [unitaryHACK] on the title!

> I am hoping to solve issue(s) labelled for UnitaryHack too! I thought of this small change while I was going through the source code.
> 
> Could you let me know your thoughts? :)

That will depend on your physics and quantum computing knowledge... DM me in Discord (HGSilveri) if you want to discuss further.

**Comment by Yash-10** [comment]
> Then don't forget to write [unitaryHACK] on the title!

Oh, thanks for that. I have added it in the title.


> That will depend on your physics and quantum computing knowledge... DM me in Discord (HGSilveri) if you want to discuss further.

Thanks, I shall do so after picking up an issue.

**Comment by HGSilveri** [comment]
While we're at it, we should get rid of all unnecessary `format` cases. I looked for them in the code and found two more:

- pulser/sequence.py, line 373
- pulser/_seq_drawer.py, line 98

Do you think you could change these too? Thanks!

**Comment by Yash-10** [comment]
Thanks, I think the change in`sequence.py` got reverted after I rebased earlier. Now it seems to be addressed?

**Review by HGSilveri — APPROVED** [review]
LGTM, thanks for the contribution!

**Comment by HGSilveri** [comment]
> Thanks, I think the change in`sequence.py` got reverted after I rebased earlier. Now it seems to be addressed?

All looks good, thanks!

**Pull request merged**
