### PR TITLE
Applying SLM mask for the state preparation on the XXZ quantum simulation tutorial

### PR DESCRIPTION
**Pull request by lhenriet**
Hello ! I added the SLM mask feature for the preparation of DW state.

### CODE REVIEW

**Comment by HGSilveri** [comment]
@lhenriet Thanks a lot for these changes! When you presented this tutorial, I have a vague recollection of there being a typo on the label of some plot, but now I can't seem to find it. Does this ring a bell? Did you fix it back then, am I missing it or just confusing things?

**Comment by Louis-PaulHenry** [comment]
It looks good to me. I've jsut put one remark concerning one of the plots. Having implementing the mask makes it smoother!

**Comment by lhenriet** [comment]
> @lhenriet Thanks a lot for these changes! When you presented this tutorial, I have a vague recollection of there being a typo on the label of some plot, but now I can't seem to find it. Does this ring a bell? Did you fix it back then, am I missing it or just confusing things?

Thanks for reminding me of that ! Factor 1/2 added to a plot axis label.

**Comment by HGSilveri** [comment]
@Louis-PaulHenry Go to go?

**Review by Louis-PaulHenry — APPROVED** [review]

**Pull request merged**
