### PR TITLE
Updates to `pulser.sampler`

### PR DESCRIPTION
**Pull request by HGSilveri**
- Separates the specific noise definitions from general noise objects to isolate `pulser.sampler` and `pulser.simulation`
- Adds missing license headers

### CODE REVIEW

**Review by lvignoli — COMMENTED** [review]
When the simulation module will be an extra package, one would have to install it to sample a sequence with the amplitude or doppler noises.
It is what we want?

**Comment by HGSilveri** [comment]
> When the simulation module will be an extra package, one would have to install it to sample a sequence with the amplitude or doppler noises. It is what we want?

Yes, I would say so, mainly because sampling with noises is something that's essentially used for simulation. 
Bear in mind, however, that I plan on keeping the default `pulser` installation include the simulation features.

**Review by lvignoli — APPROVED** [review]
Ok then!

If the number of noises grows too much, maybe they will deserve their own module.

**Comment by lvignoli** [comment]
Oops sorry I missed it too :/

**Pull request merged**
