### PR TITLE
fixed harmless typo in create_random_graphs

### PR DESCRIPTION
**Pull request by darcangelomauro**
See issue #301

### CODE REVIEW

**Comment by darcangelomauro** [comment]
I'M not really sure why the checks are not passing, I only changed a line in the qek notebook

**Comment by HGSilveri** [comment]
> I'M not really sure why the checks are not passing, I only changed a line in the qek notebook

Might be due to a new version of `mypy`, I'll take care of it

**Comment by HGSilveri** [comment]
I'm addressing this in #304, it should be a matter of merging those in here once that's done.

**Review by HGSilveri — APPROVED** [review]
LGTM, thanks for spotting this!

**Pull request merged**
