### PR TITLE
Release v15.3

### PR DESCRIPTION
**Pull request by a-corni**
Making a hot fix to enable the use of parametrized phase in eom mode.

### CODE REVIEW

**Review by madagra — APPROVED** [review]
LGTM.

**Comment by madagra** [comment]
@a-corni you should likely use MyPy v1.6.1 in order to make the tests pass.

**Comment by a-corni** [comment]
The error seems to be coming from the module [referencing](https://pypi.org/project/referencing/0.31.0/#history). They made a new release on Nov. 14th and the error shown (see below) points directly to it according to this [issue on mypy](https://github.com/python/mypy/issues/12299)

> /opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/referencing/jsonschema.py:499: error: Invalid "type: ignore" comment  [syntax]

I have followed what the mypy developpers suggested there: Add to mypy.ini:

> [mypy-discord.*]
follow_imports = skip

But this does not seem to have changed anything - which is weird, it should have deleted the error messages coming from referencing,

**Comment by a-corni** [comment]
> The error seems to be coming from the module [referencing](https://pypi.org/project/referencing/0.31.0/#history). They made a new release on Nov. 14th and the error shown (see below) points directly to it according to this [issue on mypy](https://github.com/python/mypy/issues/12299)
> 
> > /opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/referencing/jsonschema.py:499: error: Invalid "type: ignore" comment  [syntax]
> 
> I have followed what the mypy developpers suggested there: Add to mypy.ini:
> 
> > [mypy-discord.*]
> > follow_imports = skip
> 
> But this does not seem to have changed anything - which is weird, it should have deleted the error messages coming from referencing...

Solved by using `skip` instead of `silent` (it makes a difference in the end)

**Pull request merged**
