### PR TITLE
WIP: simulation with samples from pulser.sampler.sample()

### PR DESCRIPTION
**Pull request by lvignoli**
Draft PR for substituting the legacy sampling in the `Simulation` class with the dedicated `pulser.sampler` module.

It is in particular a prerequisite to simulation of modulated sequence (see #315).

Blindly substituting the core of `Simulation._extract_samples()` with `pulser.sampler.sample()` does not work: weirdly the final state of the two simulations differ by the number of levels considered, the new one outputting a 3-level state.
Also, restricted to the first 2 components, they are numerically not the same at 1e-3 accuracy.

I have been unable to pinpoint where the divergence occurs.

Run the notebook `tutorials/simulation_with_sampler.ipynb` to see the issue in action.

### CODE REVIEW

**Comment by HGSilveri** [comment]
Thanks! I'll take a look

**Comment by HGSilveri** [comment]
@lvignoli I found the culprit: `Simulation._build_basis_and_op_matrices()` relies on the dictionary for a given basis being empty to determine whether to ignore that basis (e.g. if `samples["Global"]["digital"] == {}`, it will make a two-level system with just the `ground-rydberg` basis). 
The problem is that the sampler is using a `defaultdict`, so when you check for e.g. `samples["Global"]["digital”]` it populates it (with arrays of 0s, but still) and so assumes the `digital` basis is also being used.

**Comment by HGSilveri** [comment]
> Actually this can't be the fix, since any key is valid in the `defaultdict`, and even read operation modify the `defaultdict` by adding a zero value for the read keys.
> 
> Why not simply getting rid of the `defaultdict`? I am unsure of the exact reason they are here in the first place, probably because it was much easier to test since it provides default zero values.

I think they make for a cleaner implementation by avoiding the recurrent check of whether a given key is already in the dictionary or not, but this shouldn't come at the expense of complicating things down the road. 

In this case, however, I would maybe add that relying on the samples to determine the basis being used is not the most robust approach here. I would maybe suggest we change `Simulation._build_basis_and_op_matrices()` to look at the bases of the declared channels instead.

**Comment by lvignoli** [comment]
I back the change for `Simulation._build_basis_and_op_matrices()`.

But I am still a bit concern about the defaultdicts, since

```python
_ = samples["Global"]["whatever-channel-🦄"]["amp"]
```

is a valid call to the `samples` dictionary, returning an array of zeros. Worse, everytime one tries to read a non-existing value, it instantiates a numpy array of zeros for "amp", "det" and "phase" for this new key, and any future loop over the keys will have to deal with this.

It is tricky stuff…

**Comment by HGSilveri** [comment]
> But I am still a bit concerned about the defaultdicts, since
> 
> ```python
> _ = samples["Global"]["whatever-channel-🦄"]["amp"]
> ```
> 
> is a valid call to the `samples` dictionary, returning an array of zeros. Worse, everytime one tries to read a non-existing key, it instantiates a numpy array of zeros for "amp", "det" and "phase" for this new key, and any future loop over the keys will have to deal with this.
> 
> It is tricky stuff…

Yes, I understand your concerns. What if you convert the `defaultdict`s to `dict`s right before you return the samples?

**Comment by lvignoli** [comment]
We could do that, we have to introspect the samples nested dict for non-zero basis keys, discard them if the three amp, let and phase samples are all zeros, and then assign the regular dict with retained keys in place.

It is not that bad, but given the supplementary intricacy, I seriously reconsider the use of `defaultdict` in the first place, if, aside from testing, it is just to get rid of them with overcomplicated code in the end.

**Comment by HGSilveri** [comment]
> We could do that, we have to introspect the samples nested dict for non-zero basis keys, discard them if the three amp, det and phase arrays are all zeros, and then assign the regular dict with retained keys in place.

I don't think it needs to be that complicated. Wouldn't [this simple solution](https://stackoverflow.com/questions/26496831/how-to-convert-defaultdict-of-defaultdicts-of-defaultdicts-to-dict-of-dicts-o) do the trick?

**Comment by lvignoli** [comment]
Okay it sounded bad to my ears when describing it but yeah it is not that bad one you just _write_ it

**Comment by lvignoli** [comment]
Still, it's weird to have them just to discard them

Do you find a place in the `pulser.sampler` code where we actually benefit from having a default zero value for non existing keys?

**Comment by lvignoli** [comment]
Okay it makes the [`_write_dict()`](https://github.com/pasqal-io/Pulser/blob/2b49cf4b6156ed3724777fcc56b08bf07108edfe/pulser-core/pulser/sampler/sampler.py#L141) function straightforward, but that's it for me

**Comment by lvignoli** [comment]
@HGSilveri all good on the `defaultdicts` now.

Still puzzled by the additional zero sample, should we revive the eternal discussion with @sebgrijalva?

**Comment by lvignoli** [comment]
Added the additional 0 samples through the `additional_zero_sample` flag.

Still miss tests.

**Review by HGSilveri — COMMENTED** [review]
Looks pretty solid!

**Comment by HGSilveri** [comment]
A new PR will be opened incorporating the changes introduced in #388

**Pull request closed without merging**
